services:
  corrections-postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: fixme
      POSTGRES_USER: fixme
      POSTGRES_PASSWORD: fixme
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - corrections-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      start_period: 10s
      start_interval: 1s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  corrections-postgres-data:
